### PR TITLE
exynos7885: a*: use inclusive bitwise OR operator in OTA asserts

### PR DESCRIPTION
**Pull request by FraSharp**
Signed-off-by: FraSharp <s23265@iisve.it>

### CODE REVIEW

**Comment by Chatur27** [comment]
@FraSharp What is this

**Comment by FraSharp** [comment]
using | instead of ,

**Comment by Chatur27** [comment]
> using | instead of ,

My bad
GIthub Bot replied for me xD

**Comment by FraSharp** [comment]
lmao

**Comment by el0xren** [comment]
@FraSharp bruh

**Comment by FraSharp** [comment]
what

**Comment by el0xren** [comment]
@FraSharp mistake sorry

**Comment by FraSharp** [comment]
😸

**Pull request merged**
